version: '3.8'

services:
  backend:
    image: ghcr.io/chashkakefira/seating-generator-backend:latest
    container_name: seating-backend
    ports: 
      - "8091:8080"

  frontend:
    image: ghcr.io/chashkakefira/seating-generator-frontend:latest
    container_name: seating-frontend
    ports:
      - "8092:80"
    environment: 
      - VITE_API_URL=http://localhost:8091/api/generate-seating
    depends_on: 
      - backend
