# Copyright (C) 2026 Прокофьев Даниил <danieldzen@yandex.ru>
# Лицензировано под GNU Affero General Public License v3.0
# Часть проекта генератора рассадок
services:
  backend:
    image: ghcr.io/dvprokofiev/seating-generator-backend:latest
    container_name: seating-backend
    ports: 
      - "8091:5000"

  frontend:
    image: ghcr.io/dvprokofiev/seating-generator-frontend:latest
    container_name: seating-frontend
    ports:
      - "8092:80"
    depends_on: 
      - backend
